"""change the duration_work attribute to start_date

Revision ID: 24525389652f
Revises: 3d165f029b39
Create Date: 2025-05-17 01:06:36.082795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24525389652f'
down_revision: Union[str, None] = '3d165f029b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacture', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('manufacture', 'duration_work')
    op.alter_column('resource', 'ready_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'ready_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('manufacture', sa.Column('duration_work', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('manufacture', 'start_date')
    # ### end Alembic commands ###
