"""adding new attributes to the manufacture table

Revision ID: 325ead635008
Revises: 75381460c3a4
Create Date: 2025-05-14 12:25:46.511328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325ead635008'
down_revision: Union[str, None] = '75381460c3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacture', sa.Column('success_orders', sa.Integer(), nullable=True))
    op.add_column('manufacture', sa.Column('failed_orders', sa.Integer(), nullable=True))
    op.add_column('manufacture', sa.Column('duration_work', sa.Integer(), nullable=True))
    op.alter_column('manufacture', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('manufacture', 'geoip_lat',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('manufacture', 'geoip_lon',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manufacture', 'geoip_lon',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('manufacture', 'geoip_lat',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('manufacture', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('manufacture', 'duration_work')
    op.drop_column('manufacture', 'failed_orders')
    op.drop_column('manufacture', 'success_orders')
    # ### end Alembic commands ###
