"""Fix relationships in models

Revision ID: 75381460c3a4
Revises: 
Create Date: 2025-04-08 02:21:51.569536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75381460c3a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('manufacture_user_user_id_key', 'manufacture_user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('manufacture_user_user_id_key', 'manufacture_user', ['user_id'])
    # ### end Alembic commands ###
