"""adding time until ready to the Resource table

Revision ID: 8cc54ec83626
Revises: 325ead635008
Create Date: 2025-05-14 12:59:45.675916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc54ec83626'
down_revision: Union[str, None] = '325ead635008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('ready_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'ready_time')
    # ### end Alembic commands ###
