"""removing the type_resources attribute from the Resource table

Revision ID: b090ad0fbd84
Revises: 8cc54ec83626
Create Date: 2025-05-14 13:45:41.878771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b090ad0fbd84'
down_revision: Union[str, None] = '8cc54ec83626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'resource_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('resource_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
