"""change primary_key and removing the id attribute in the Resource table

Revision ID: dbf26f12855c
Revises: b090ad0fbd84
Create Date: 2025-05-14 15:32:12.707990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf26f12855c'
down_revision: Union[str, None] = 'b090ad0fbd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'ready_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('resource', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('resource', 'ready_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
